### ISSUE TITLE
Renders not full screen on my Nexus 5X emulator

### ISSUE THREAD

**Issue by solid-software** [valeriypolezhay/solidSoftwareTask#1]
Renders not full screen on my Nexus 5X emulator.

Please see screenshot attached.
![screenshot_1532954763](https://user-images.githubusercontent.com/40825054/43398145-e01e6900-940f-11e8-8479-36c407550cc2.png)

**Comment by valeriypolezhay** [comment]
Fixed. New version in the repository. Now everything should be fine.



пн, 30 июл. 2018 г. в 15:48, Solid Software <notifications@github.com>:
